export const SHOW_TOAST_NOFITICATION = "SHOW_TOAST_NOFITICATION"
export const REMOVE_TOAST_NOFITICATION = "REMOVE_TOAST_NOFITICATION"
export const SET_USER_DETAIL = "SET_USER_DETAIL"
export const REMOVE_USER_DETAIL = "REMOVE_USER_DETAIL"
export const SET_LOADER = "SET_LOADER"
export const SET_COUNTRY_DETAILS = "SET_COUNTRY_DETAILS"
export const REMOVE_COUNTRY_DETAILS =  "REMOVE_COUNTRY_DETAILS"

