// Layout Type
export const HANDLE_CONTENT_WIDTH = "HANDLE_CONTENT_WIDTH"
export const HANDLE_MENU_COLLAPSED = "HANDLE_MENU_COLLAPSED"
export const HANDLE_MENU_HIDDEN = "HANDLE_MENU_HIDDEN"
export const HANDLE_RTL = "HANDLE_RTL"
export const HANDLE_ONLINE_USER_HIDDEN = "HANDLE_ONLINE_USER_HIDDEN"
export const ADD_EDIT_POPUP = "ADD_EDIT_POPUP"
export const ADD_EDIT_POPUP_DATA = "ADD_EDIT_POPUP_DATA"

// Tost types
export const SHOW_TOAST_NOFITICATION = "SHOW_TOAST_NOFITICATION"
export const REMOVE_TOAST_NOFITICATION = "REMOVE_TOAST_NOFITICATION"

// users types
export const SET_USER_DETAIL = "SET_USER_DETAIL"
export const REMOVE_USER_DETAIL = "REMOVE_USER_DETAIL"
export const SET_LOADER = "SET_LOADER"
export const SET_COUNTRY_DETAILS = "SET_COUNTRY_DETAILS"
export const REMOVE_COUNTRY_DETAILS =  "REMOVE_COUNTRY_DETAILS"
export const SET_ONLINE_USERS = "SET_ONLINE_USERS"
export const UPDATE_ONLINE_USERS = "UPDATE_ONLINE_USERS"
export const REMOVE_ONLINE_USERS = "REMOVE_ONLINE_USERS"
export const UPDATE_OFFLINE_USERS = "UPDATE_OFFLINE_USERS"
export const SET_ALL_USERS = "SET_ALL_USERS"

// CHATS TYPE
export const SET_USERS_ROOMS = "SET_USERS_ROOMS"
export const SET_GLOBAL_MESSAGES = "SET_GLOBAL_MESSAGES"

// LAYOUT SETTINGS
export const SET_LAYOUT_SETTINGS = "SET_LAYOUT_SETTINGS"
export const SET_TOTAL = "SET_TOTAL"
export const SET_LAYOUT_SETTING = "SET_LAYOUT_SETTING"